### ISSUE TITLE
Buggy interaction between OneShot modifiers and non-OneShot layer keys

### ISSUE THREAD

**Issue by cdisselkoen** [keyboardio/Kaleidoscope-OneShot#10]
Non-OneShot layer keys can get "stuck" in the pressed position when used in combination with OneShot modifiers.

Steps to reproduce:
1. Flash the 'example' firmware from this repo.  I've reproduced the problematic behavior using the most recent version of this plugin, 2fe4ef3.
2. Attempt to type Ctrl-RightArrow using the oneshot functionality.  Namely, tap the OSM(LeftControl) key, then hold the left Fn key (note it is not a OneShot in this sketch) and tap 'L'.  Observe that this works as expected; Ctrl-RightArrow is input.
3. Type any of 'H', 'J', 'K', 'L'.  Observe that the Fn key is 'stuck' due to the previous key sequence, and therefore these keys produce arrows rather than their letters.
4. Even though it is not a OneShot key, tapping Fn again 'resets' it, so the keyboard resumes functioning normally.

**Comment by algernon** [comment]
On second thought... this might be related to #11 after all!

When you tap `OSM(LeftControl)` followed by holding the `Fn` key it activates the `Fn` layer, and masks the `Fn` key - meaning any event generated by it will be ignored until it is tapped again. When you tap `L`, that works as expected, because we are on the correct layer.

When you tap `H`, `J`, `K`, or `L`, then due to the masking, the `Fn` layer will still be active. Then, when you tap `Fn` the press activates the layer (a no-op in this case), and deactivates it on release.

So, uuhhh. The root cause is the same feature, the masking. The fix is likely going to be different though.

**Comment by cdisselkoen** [comment]
Perhaps my proposed alternate-fix for #4 (see comments there) would fix this as well?  Since we would eliminate masking, we would never mask Fn, so its key-up signal should be processed normally.

**Comment by algernon** [comment]
It would fix this, but introduce other issues :|

I can very easily fix this one, though: the masking code currently clears the mask on key release, but prevents any further action. If I change that to clear the mask on release, but let the event through, that fixes this issue. But not #11 yet.
