### ISSUE TITLE
sometimes doesn't stick on first try

### ISSUE THREAD

**Issue by ToyKeeper** [keyboardio/Kaleidoscope-OneShot#12]
Sometimes OneShot mode doesn't activate on the first try, and takes two modifier presses to activate instead.  I'm not sure exactly what causes this, but I at least found a reliable way to make it happen:

1. Hold Fn.
2. Press and release an arrow key three times.
3. Release Fn.
4. Tap (quickly press and release) a mod key.

Expected results: The tapped mod key should "stick".

Actual results:  The tapped mod key doesn't stick on the first try.  It does stick if tapped again though.

Oddly enough, timing doesn't seem to matter for this test.  I can wait several seconds between each step and the results are the same.

**Comment by algernon** [comment]
Reproduced. Likely has something to do with `hold_time_out`, because I can reproduce this with only `Fn`:

1. Hold `Fn`.
2. Wait longer than `hold_time_out`.
3. Release `Fn`.
4. Tap `Fn` (or any other modifier), and it will not remain active.

It will briefly flash into activity (for about a scan cycle), but then it cancels. So something about `hold_time_out` is buggy by the looks of it. My suspicion is that we don't clear a timer, so when we activate a one-shot again, the plugin will immediately think we are past the timeout, and cancel it at the end of the cycle.

**Comment by algernon** [comment]
Fix incoming in a bit. Meanwhile, a little explanation of what caused the issue, and what the fix is:

When we hold a `OneShot` key (any oneshot key, modifier or layer doesn't matter) for longer than the normal timeout, a main loop hook will flip the `should_cancel_` flag on. As long as the key is held, we will not act on it, but will keep the flag set. When we release the key after `hold_time_out`, we immediately clear the one-shot effect, and don't wait until the end of the scan cycle. So when we get to the scan cycle, the one-shot effect is already off, and it will be a big no-op. Next time we press and release a one-shot key (any one-shot key), with the intent of enabling the one-shot effect, on press, we will enable the one-shot effect, and in the loop hook, we'll look at `should_cancel_`, and discover it is set, and disable the effect.

This is why the issue happens: because there is nothing to turn the `should_cancel_` flag off in this case. When you tap the one-shot key again, the flag will already be off, because the previous - erroneous - cancel unset it. So this new tap will have the desired effect.

The fix is to clear the flag when cancelling after hold timeout.
