### ISSUE TITLE
OSL and ShiftToLayer()

### ISSUE THREAD

**Issue by Jennigma** [keyboardio/Kaleidoscope-OneShot#15]
How does OSL interact with the new ShiftToLayer() ? Will OSL(ShiftToLayer(FUNCTION)) work?

**Comment by obra** [comment]
ShiftToLayer is the same as the old Key_Keymap#_Momentary calls. If it worked with that, it should work with these

**Comment by algernon** [comment]
No, it will not work that way. `OSL` is orthogonal to `ShiftToLayer` and `LockLayer`, as in its a third kind of layer switching behaviour. You can't combine these three on the same key. `ShiftToLayer(LockLayer(FUNCTION))` makes no sense either. 

All of these things tell the firmware to switch to another layer (and the argument must therefore be a layer), the difference is what happens after: with `LockLayer`, it stays there until unlocked; with `ShiftToLayer`, it stays there until the key is held; with `OSL`, it stays there until the next non-oneshot key activates. You can't compose them, because their behaviour is not composable. You can have all of them on the same keymap, on different keys, but there is no such thing as a one-shot, shifted layer key. Mind you, `OSL` will behave as `ShiftToLayer` while held.

Furthermore, as `ShiftToLayer(FUNCTION)` results in a keycode, and not a layer index, `OSL(ShiftToLayer(FUNCTION))` would try to switch to layer number 53426 or something like that.

Does this answer your question?

**Comment by Jennigma** [comment]
Oh! So I just want OSL(FUNCTION), correct?

The behavior I'm hoping for is to eg tap it once and then tap N to mute the computer, or to tap it twice to mouse or arrow around and then tap it again to drop back to the QWERTY layer.

**Comment by Jennigma** [comment]
Yup! working. 

And fwiw @obra  It's building through the Arduino IDE.

**Comment by algernon** [comment]
Glad to hear it is working! Closing then =)
