### ISSUE TITLE
Add modifier to allow left/right pairs to cancel each other

### ISSUE THREAD

**Issue by Jennigma** [keyboardio/Kaleidoscope-OneShot#16]
ISSUE: If R SHIFT is double tapped, L SHIFT won't release it. 

Some folks will prefer this behavior, while others will prefer to have the modifier pairs cancel each other.

PROPOSAL: Add a configuration option to the plugin that allows users to choose how the left/right pairs work.

WORKAROUND: use only "L" or only "R" modifier pairs in the keymap.

**Comment by algernon** [comment]
I may or may not get around to do this, but in case someone else wants to work on it, [these macros](https://github.com/keyboardio/Kaleidoscope-OneShot/blob/91971489cf1a19fdc8346dea688de002e579d2ce/src/Kaleidoscope/OneShot.cpp#L47-L49) are the key points to work with.

Turning them into functions, and making them support canceling the other part of the pair is best done here. So `isSticky` would return true for both modifiers if either is sticky, something like `bitRead(sticky_state_.all, idx) || bitRead(sticky_state_.all, idx + 4)` (except smarter, but you get the idea), `setSticky` needs no change, because we only want to activate one of them, not both, and `clearSticky` would just clear both flags.

So the "hardest" part is `isSticky`, and even that should be reasonably straightforward. Then, push this behind a boolean toggle, and make it default to off, update the `README.md`, and you are done.

If anyone's up for it, I'm happy to offer further hints. =)

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#424.
