### ISSUE TITLE
OneShot.cancel(true) does not work

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope-OneShot#17]
`OneShot.cancel(true)` should cancel stickies too, but it does not work, the stickies remain active.

**Comment by glasser** [comment]
Specifically it shifts them to non-sticky active. I think that it needs a cancelOneShot after the clearSticky?

**Comment by algernon** [comment]
I was thinking the same, but `cancelOneShot` after the `clearSticky` didn't fix it either. :|

**Comment by glasser** [comment]
OK, so what I noticed (with OneShot, ActiveModColor, and Escape-OneShot) was that when I added `cancelOneShot` after `clearSticky` (and added the `cancel(true)` to Escape-Oneshot), that escaping a sticky left the key in "normal one-shot" highlight color, but it didn't actually seem to affect other keys.

Adding a `clearPressed` as well seems to fix that. However, maybe that line should be added to cancelOneShot instead of to the loopHook? I dunno. This whole thing could use some refactoring, I think. It confuses me.

**Comment by algernon** [comment]
> This whole thing could use some refactoring, I think. It confuses me.

100% agreed. It confuses the hell out of me too, and I wrote it.

Thanks for experimenting, that helps me immensely! I'll try to fix things this week, whenever time allows. With the research you did, it should be a whole lot easier. \o/
